/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx}",
    "./src/**/*.{ts,tsx}",
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        sm: "640px",
        md: "738px",
        lg: "1024px",
        xl: "1280px",
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        "black-pearl": {
          50: "#F4F6FB",
          100: "#E7EDF7",
          200: "#CAD9ED",
          300: "#9CBADD",
          400: "#6796C9",
          500: "#4378B4",
          600: "#325F97",
          700: "#294C7B",
          800: "#264266",
          900: "#243956",
          950: "#0F1724",
        },
        "bright-turquoise": {
          50: "#EEFFFD",
          100: "#C5FFFA",
          200: "#8BFFF8",
          300: "#48FFF4",
          400: "#11ECE5",
          500: "#00D2CE",
          600: "#00A9A9",
          700: "#008386",
          800: "#0568GA",
          900: "#0A5557",
          950: "#003336",
        },
        iron: {
          50: "#F5F7F8",
          100: "#EDEFF2",
          200: "#DFE2E6",
          300: "#D1D5DB",
          400: "#B5B9C4",
          500: "#A1A5B3",
          600: "#8B8FA0",
          700: "#777A8B",
          800: "#626471",
          900: "#52555D",
          950: "#303136",
        },
        "gray-chateau": {
          50: "#F5F7F8",
          100: "#EEEFF1",
          200: "#DFE2E6",
          300: "#CBD1D6",
          400: "#B4BBC4",
          500: "#9CA3AF",
          600: "#8B90A0",
          700: "#787D8A",
          800: "#626671",
          900: "#52555D",
          950: "#303236",
        },
        turquoise: {
          50: "#F3FEFD",
          100: "#E6FDFC",
          200: "#C1F9F7",
          300: "#9CF6F2",
          400: "#52EFE8",
          500: "#08E8DE",
          600: "#07D1C8",
          700: "#058B85",
          800: "#046864",
          900: "#024643",
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      flexBasis: {
        "1/9": "11.11111111%",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
    fontFamily: { sans: ["Nunito", "sans-serif"] },
  },
  plugins: [require("tailwindcss-animate")],
};
